# Generated by Django 3.0.8 on 2021-05-22 14:14

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='file',
            field=models.FileField(null=True, upload_to=Projects.models.path_and_rename),
        ),
    ]
