# Generated by Django 3.0.8 on 2021-05-22 14:42

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20210522_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Projects.models.path_and_rename),
        ),
    ]
