# Generated by Django 3.0.8 on 2021-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20210409_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='author',
            field=models.TextField(null=True),
        ),
    ]
