# Generated by Django 3.0.8 on 2021-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20210522_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
