# Generated by Django 3.0.8 on 2021-05-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20210522_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject',
            name='file',
        ),
    ]
