# Generated by Django 3.0.8 on 2021-05-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_remove_myproject_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='facultyId',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
