# Generated by Django 3.0.8 on 2021-05-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_myproject_facultyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
